"""edit review table

Revision ID: 4dbaf5ec8dc9
Revises: 0105290f8614
Create Date: 2024-12-17 21:08:38.334731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dbaf5ec8dc9'
down_revision = '0105290f8614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', mysql.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
